version: '3.7'
services: 
    sonarqube:
        image: sonarqube:8.4.2-community
        ports:
            - 9000:9000
        volumes: 
            - ./volumes/sonarqube_data:/opt/sonarqube/data
            - ./volumes/sonarqube_extensions:/opt/sonarqube/extensions
            - ./volumes/sonarqube_logs:/opt/sonarqube/logs

    buildenv:
        build: 
            context: .
            dockerfile: ./buildenv/Dockerfile